stages:
    - deploy

eas_update:
    stage: deploy
    rules:
        - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "develop")
          when: on_success
        - when: never
    script:
        - echo "Setting up environment..."
        - apt-get update && apt-get install -y curl git
        - curl -sL https://deb.nodesource.com/setup_20.x | bash -
        - apt-get install -y nodejs
        - npm install -g expo-cli eas-cli
        - npm install
        - echo "Running EAS Update..."
        - if [ "$CI_COMMIT_BRANCH" = "staging" ]; then
          NODE_ENV=staging eas update --branch staging --message "Update from commit $CI_COMMIT_SHORT_SHA";
          elif [ "$CI_COMMIT_BRANCH" = "develop" ]; then
          NODE_ENV=development eas update --branch develop --message "Update from commit $CI_COMMIT_SHORT_SHA";
          fi
    variables:
        EXPO_TOKEN: $EXPO_TOKEN
