stages:
    - deploy

eas_update:
    stage: deploy
    rules:
        - if: $CI_MERGE_REQUEST_IID && $CI_COMMIT_BRANCH == "staging"
        - if: $CI_MERGE_REQUEST_IID && $CI_COMMIT_BRANCH == "develop"
    script:
        - echo "Setting up environment..."
        - npm install
        - npm install -g eas-cli
        - echo "Running EAS Update..."
        - if [ "$CI_COMMIT_BRANCH" = "staging" ]; then
          eas update --branch staging --message "Update from MR $CI_MERGE_REQUEST_IID ($CI_COMMIT_SHORT_SHA)";
          elif [ "$CI_COMMIT_BRANCH" = "develop" ]; then
          eas update --branch develop --message "Update from MR $CI_MERGE_REQUEST_IID ($CI_COMMIT_SHORT_SHA)";
          fi
    environment:
        name: production
    variables:
        EXPO_TOKEN: $EXPO_TOKEN
    only:
        - merge_requests
