name: EAS Update

on:
    pull_request:
        types: [closed]
        branches:
            - staging
            - develop

jobs:
    eas_update:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install

            - name: Install EAS CLI
              run: npm install -g eas-cli

            - name: Set Expo Token
              id: set_token
              run: |
                  if [[ "${{ github.ref_name }}" == "staging" ]]; then
                    echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN_STAGING }}" >> $GITHUB_ENV
                  elif [[ "${{ github.ref_name }}" == "develop" ]]; then
                    echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN_DEVELOP }}" >> $GITHUB_ENV
                  fi

            - name: Run EAS Update
              env:
                  EXPO_TOKEN: ${{ env.EXPO_TOKEN }}
              run: |
                  if [[ "${{ github.ref_name }}" == "staging" ]]; then
                    eas update --branch staging --message "Update for staging branch"
                  elif [[ "${{ github.ref_name }}" == "develop" ]]; then
                    eas update --branch develop --message "Update for develop branch"
                  fi
